sonar.projectKey=fiber-pr1
sonar.projectName=fiber-pr1
sonar.projectVersion=1.0

# Path to source files
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,docs/**

# Go specific configuration
sonar.go.coverage.reportPaths=coverage.out
sonar.go.tests.reportPaths=report.json

# Language
sonar.sourceEncoding=UTF-8
